site_name: crypto-invest-portfolio
repo_url: https://github.com/apajon/crypto-invest-portfolio
site_url: https://apajon.github.io/crypto-invest-portfolio
site_description: This is a repository python project of a crypto investment portfolio.
site_author: Adrien Pajon
edit_uri: edit/main/docs/
repo_name: apajon/crypto-invest-portfolio
copyright: Maintained by <a href="https://apajon.com">apajon</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/crypto_invest_portfolio"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/apajon/crypto-invest-portfolio
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/crypto-invest-portfolio

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
